Data bilan tanishuv

In [5]:
import pandas as pd  # pyright: ignore[reportUnusedImport]

In [6]:
df=pd.read_csv('upcoming-ultra-trails.csv')

In [9]:
df.head(5)

,event_date,name,distance_km,elevation_gain_m,elevation_loss_m,gpx_url,event_name,country,locality,source_url,source,schema_version,scraped_at
0,2026-10-26,Mandala Spirit I,305.44,23294.0,22609.0,https://tracedetrail.fr/fr/trace/361139,Mandala Spirit,NPL,Laprak,https://itra.run/Races/RaceDetails/Mandala.Spi...,itra,1,2026-10-25T17:00:46+00:00
1,2026-10-26,Ultramarathon,63.00,1300.0,1300.0,NaN,Röntgenlauf,DEU,Remscheid,https://itra.run/Races/RaceDetails/R%C3%B6ntge...,itra,1,2026-10-25T17:00:46+00:00
2,2026-10-29,35th Himalayan 100 Mile Stage Race,161.00,7000.0,6990.0,https://tracedetrail.fr/fr/trace/337178,HIMALAYAN 100 MILE STAGE RACE,IND,manebhanjyang,https://itra.run/Races/RaceDetails/HIMALAYAN.1...,itra,1,2026-10-25T17:00:46+00:00
3,2026-10-29,5th Himalayan 100 K Stage Race,100.00,4170.0,5310.0,https://tracedetrail.fr/fr/trace/337183,HIMALAYAN 100 MILE STAGE RACE,IND,manebhanjyang,https://itra.run/Races/RaceDetails/HIMALAYAN.1...,itra,1,2026-10-25T17:00:46+00:00
4,2026-10-30,100,163.69,9060.0,9275.0,https://tracedetrail.fr/fr/trace/331346,LAKE BIWA 100,JPN,Komonocho,https://itra.run/Races/RaceDetails/LAKE.BIWA.1...,itra,1,2026-10-25T17:00:46+00:00

In [10]:
df.tail(5)

,event_date,name,distance_km,elevation_gain_m,elevation_loss_m,gpx_url,event_name,country,locality,source_url,source,schema_version,scraped_at
1228,2027-10-16,Blackall50,52.25,1746.0,1746.0,https://tracedetrail.fr/fr/trace/363698,The Blackall100,AUS,MAPLETON,https://itra.run/Races/RaceDetails/The.Blackal...,itra,1,2026-10-25T17:00:46+00:00
1229,2027-10-16,PÉTRA WADI RUM TRAIL CHALLENGE,113.00,3150.0,2650.0,NaN,PÉTRA WADI RUM TRAIL CHALLENGE Trail To Be Alive,JOR,Madaba,https://itra.run/Races/RaceDetails/P%C3%89TRA....,itra,1,2026-10-25T17:00:46+00:00
1230,2027-12-04,110km,110.00,3042.0,3008.0,NaN,Ultra X Rwanda,RWA,Ruhondo,https://itra.run/Races/RaceDetails/Ultra.X.Rwa...,itra,1,2026-10-25T17:00:46+00:00
1231,2027-12-04,50km,50.00,902.0,1426.0,NaN,Ultra X Rwanda,RWA,Ruhondo,https://itra.run/Races/RaceDetails/Ultra.X.Rwa...,itra,1,2026-10-25T17:00:46+00:00
1232,2027-12-04,Pharaons Pyramids Trail,69.00,590.0,NaN,NaN,Pharaons Pyramids Trail Trail To Be Alive,EGY,Al Qahirah al Jadidah,https://itra.run/Races/RaceDetails/Pharaons.Py...,itra,1,2026-10-25T17:00:46+00:00

In [14]:
df['name'].unique()

<StringArray>
[                  'Mandala Spirit I',                      'Ultramarathon',
 '35th Himalayan 100 Mile Stage Race',     '5th Himalayan 100 K Stage Race',
                                '100',                              '100KM',
                              '100km',                           '100miles',
                              '168km',                                '50K',
 ...
                               'L120',                                'E50',
                                'M70',                   'Trail des 3 cols',
                   '110km Adventurer',                   '50km Night Ultra',
                        'Blackall100',                         'Blackall50',
    'PÉTRA WADI RUM TRAIL  CHALLENGE',           'Pharaons Pyramids  Trail']
Length: 1002, dtype: str

In [15]:
df['elevation_loss_m'].unique()

array([2.2609e+04, 1.3000e+03, 6.9900e+03, 5.3100e+03, 9.2750e+03,
       4.8320e+03, 1.1800e+03, 1.9800e+03, 1.1286e+04, 2.4540e+03,
       2.5560e+03, 7.9000e+02, 7.3550e+03, 8.8810e+03, 2.7000e+03,
       5.0910e+03, 1.0900e+03, 1.7200e+03, 5.4500e+03, 5.3110e+03,
       2.3920e+03, 6.1130e+03, 6.1290e+03, 7.3630e+03, 3.4900e+03,
       1.3820e+03, 3.2700e+03, 8.0000e+02, 2.5900e+03, 2.0300e+03,
       1.8570e+03, 1.5300e+03, 3.6600e+03, 3.9640e+03, 3.4800e+03,
       3.6540e+03, 4.3370e+03, 2.4730e+03, 1.3370e+03, 2.8140e+03,
       3.1300e+03, 3.8630e+03, 1.8730e+03, 2.1790e+03, 2.0000e+03,
       2.7140e+03, 2.8000e+03, 6.1900e+03, 3.6260e+03, 2.6500e+03,
              nan, 2.2000e+02, 2.7500e+02, 2.4700e+03, 2.3870e+03,
       1.8500e+03, 1.9450e+03, 2.6880e+03, 3.0000e+03, 2.0180e+03,
       4.0200e+03, 1.3750e+03, 1.2480e+03, 2.5100e+03, 2.3780e+03,
       4.1860e+03, 6.0300e+02, 8.8000e+02, 9.0300e+02, 4.8420e+03,
       1.5490e+03, 2.3360e+03, 1.1180e+03, 3.3900e+03, 6.1900e+02,
       3.7890e+03, 6.3260e+03, 2.9880e+03, 6.4840e+03, 4.2130e+03,
       5.6380e+03, 4.9520e+03, 5.7410e+03, 9.8610e+03, 1.2460e+03,
       1.8100e+03, 1.5800e+03, 3.2610e+03, 3.3400e+03, 1.8770e+03,
       2.5370e+03, 2.9930e+03, 2.6260e+03, 1.0480e+03, 2.5360e+03,
       6.4100e+02, 2.7030e+03, 1.0200e+03, 2.1410e+03, 4.1220e+03,
       1.8630e+03, 2.4800e+03, 2.2580e+03, 4.9660e+03, 1.6200e+03,
       4.2430e+03, 7.5550e+03, 2.9020e+03, 2.2320e+03, 3.1040e+03,
       3.0030e+03, 1.2840e+03, 4.2000e+03, 2.8730e+03, 2.3500e+03,
       1.3600e+03, 2.0120e+03, 1.8240e+03, 5.1200e+03, 3.4200e+03,
       5.5400e+03, 3.8710e+03, 2.8300e+03, 3.7400e+03, 9.2780e+03,
       1.1700e+03, 2.5480e+03, 2.9000e+03, 2.7670e+03, 3.4160e+03,
       1.6110e+03, 1.0640e+03, 2.1640e+03, 3.4670e+03, 1.2600e+03,
       1.0520e+03, 1.7760e+03, 2.3400e+03, 9.1000e+02, 2.0960e+03,
       1.9810e+03, 2.4510e+03, 2.6190e+03, 2.5060e+03, 2.5000e+03,
       1.3020e+03, 1.2800e+04, 5.6000e+01, 1.3880e+04, 5.7000e+03,
       8.2500e+03, 6.1000e+03, 6.1580e+03, 6.0740e+03, 8.7420e+03,
       3.8010e+03, 3.8880e+03, 1.3100e+03, 1.0000e+02, 1.4700e+03,
       1.4920e+03, 4.2890e+03, 2.9150e+03, 8.6000e+02, 2.6830e+03,
       1.9490e+03, 2.3200e+03, 3.7000e+03, 2.8930e+03, 6.8950e+03,
       1.0370e+03, 1.9350e+03, 1.1400e+03, 1.1240e+03, 2.7400e+03,
       5.6500e+03, 1.5970e+03, 2.6900e+03, 1.8250e+03, 3.9000e+03,
       1.8580e+03, 3.5730e+03, 2.9440e+03, 4.7980e+03, 1.5400e+03,
       3.5790e+03, 2.6500e+02, 5.3050e+03, 8.4750e+03, 1.4680e+03,
       1.6900e+03, 4.8000e+02, 2.0380e+03, 1.6220e+03, 2.7200e+03,
       2.3590e+03, 1.6070e+03, 1.7840e+03, 2.4570e+03, 2.7980e+03,
       2.1550e+03, 1.5790e+03, 1.9920e+03, 2.9420e+03, 2.3630e+03,
       1.3000e+02, 7.3560e+03, 2.7620e+03, 5.5250e+03, 6.0000e+02,
       1.4000e+03, 6.9910e+03, 5.1950e+03, 4.6230e+03, 4.1180e+03,
       4.3740e+03, 1.8620e+03, 1.3220e+03, 1.7570e+03, 2.8120e+03,
       8.6200e+02, 1.7960e+03, 2.2640e+03, 3.4000e+02, 5.8220e+03,
       3.0280e+03, 4.1200e+03, 5.3410e+03, 6.3000e+03, 3.1000e+03,
       1.0970e+03, 6.1300e+02, 8.8500e+02, 1.0210e+03, 1.2930e+03,
       3.4100e+02, 4.7700e+02, 3.8900e+02, 3.6490e+03, 1.9440e+03,
       3.2030e+03, 2.7060e+03, 5.0840e+03, 1.2630e+03, 1.6500e+03,
       9.7500e+02, 5.2790e+03, 2.1540e+03, 3.6800e+03, 2.6340e+03,
       2.4880e+03, 2.2700e+03, 2.6720e+03, 3.1970e+03, 2.9000e+02,
       1.4530e+03, 2.3370e+03, 1.5000e+02, 3.4940e+03, 4.4400e+03,
       8.7270e+03, 8.7320e+03, 7.5210e+03, 1.9210e+03, 2.1340e+03,
       3.3570e+03, 6.5630e+03, 3.4510e+03, 4.0970e+03, 4.3400e+03,
       6.5000e+03, 8.6600e+03, 2.2500e+03, 1.4130e+03, 1.0830e+04,
       2.7640e+03, 1.6670e+03, 3.3600e+03, 3.2490e+03, 2.3120e+03,
       3.9260e+03, 4.0900e+03, 2.5210e+03, 5.3820e+03, 4.1300e+03,
       1.5020e+03, 1.9580e+03, 3.4630e+03, 2.4720e+03, 3.0190e+03,
       2.5610e+03, 1.7990e+03, 1.9010e+03, 2.3930e+03, 2.8410e+03,
       2.5800e+03, 2.8810e+03, 2.1240e+03, 2.1500e+03, 1.6000e+03,
       2.9140e+03, 6.6700e+03, 1.0090e+04, 7.1300e+03, 4.0650e+03,
       1.0040e+03, 1.4370e+04, 4.4200e+02, 5.2600e+02, 4.3000e+03,
       8.6800e+02, 4.6930e+03, 6.8800e+03, 4.1000e+03, 5.2650e+03,
       2.1880e+03, 3.9910e+03, 5.0780e+03, 1.2860e+03, 1.2430e+03,
       2.3280e+03, 2.1700e+03, 1.3010e+03, 1.2040e+03, 1.7290e+03,
       2.5430e+03, 2.9560e+03, 2.9410e+03, 6.2580e+03, 3.3500e+03,
       3.0930e+03, 2.3520e+03, 1.8670e+03, 1.9300e+03, 1.7170e+03,
       1.2810e+03, 1.6600e+03, 2.0970e+03, 5.9100e+02, 2.6510e+03,
       2.8570e+03, 2.6350e+03, 8.4500e+02, 2.8970e+03, 2.2890e+03,
       2.6450e+03, 8.8900e+02, 1.2260e+03, 2.8850e+03, 2.1870e+03,
       1.5430e+03, 6.0300e+03, 2.6200e+03, 9.7170e+03, 2.5620e+03,
       2.7460e+03, 2.1820e+03, 3.2000e+03, 2.8500e+03, 1.2490e+03,
       4.7250e+03, 2.9950e+03, 3.5540e+03, 3.7900e+03, 2.0030e+03,
       3.1600e+03, 5.1260e+03, 5.7890e+03, 8.1110e+03, 2.8130e+03,
       4.0820e+03, 2.6540e+03, 3.0560e+03, 1.7590e+03, 5.4930e+03,
       3.8730e+03, 4.5030e+03, 2.6000e+03, 2.1750e+03, 4.0600e+03,
       8.5100e+02, 5.6000e+02, 8.8800e+02, 1.4870e+03, 4.8600e+02,
       7.4420e+03, 2.6980e+03, 4.0660e+03, 2.9620e+03, 2.0130e+03,
       9.9770e+03, 5.8530e+03, 7.9130e+03, 2.9370e+03, 3.7990e+03,
       3.8060e+03, 5.7530e+03, 2.3250e+03, 2.2850e+03, 2.6300e+03,
       7.2310e+03, 2.8390e+03, 6.5420e+03, 3.2170e+03, 1.9630e+03,
       2.9190e+03, 3.9370e+03, 5.2000e+02, 2.7610e+03, 3.7060e+03,
       8.0130e+03, 1.3330e+03, 1.9860e+03, 4.6000e+03, 2.3310e+03,
       2.5540e+03, 3.0500e+03, 3.3740e+03, 6.4550e+03, 1.5930e+03,
       1.2800e+03, 1.2000e+03, 4.7550e+03, 2.2120e+03, 2.9260e+03,
       3.3750e+03, 2.4060e+03, 4.1390e+03, 5.5290e+03, 2.3130e+03,
       4.1430e+03, 1.7230e+03, 1.5840e+03, 1.5750e+03, 2.0310e+03,
       2.7970e+03, 9.8300e+02, 2.0200e+03, 2.7500e+03, 3.1740e+03,
       2.1050e+03, 2.6310e+03, 5.8000e+02, 3.8000e+02, 2.0840e+03,
       7.1560e+03, 4.3060e+03, 3.1400e+02, 4.3250e+03, 3.0000e+02,
       2.5000e+02, 4.4080e+03, 2.3420e+03, 3.7720e+03, 3.3000e+03,
       2.7900e+02, 4.3600e+03, 2.1460e+03, 3.5040e+03, 3.0400e+03,
       1.0000e+03, 1.6460e+03, 8.5700e+02, 1.0080e+03, 1.4630e+03,
       2.2970e+03, 2.1490e+03, 5.0000e+02, 4.3430e+03, 4.1500e+03,
       2.7050e+03, 1.6680e+03, 2.1570e+03, 3.3930e+03, 4.5000e+01,
       8.4520e+03, 6.0500e+03, 4.1530e+03, 9.1700e+02, 1.8060e+03,
       1.1660e+03, 2.8030e+03, 2.5290e+03, 3.9980e+03, 2.7250e+03,
       1.8690e+03, 1.8550e+03, 1.6990e+03, 3.0840e+03, 2.2600e+03,
       3.8780e+03, 1.8000e+03, 2.4000e+04, 1.1410e+03, 4.5700e+03,
       3.0070e+03, 5.9800e+03, 4.4500e+03, 9.9000e+03, 7.2600e+03,
       8.6350e+03, 3.3100e+03, 4.5200e+03, 5.5000e+03, 3.1940e+03,
       3.7010e+03, 1.5250e+03, 1.1300e+03, 2.4440e+03, 1.6210e+03,
       2.2590e+03, 2.4010e+03, 4.6570e+03, 3.7500e+03, 7.9390e+03,
       1.9500e+03, 1.2740e+03, 4.3710e+03, 7.4300e+02, 6.9000e+01,
       8.0440e+03, 3.3290e+03, 3.2130e+03, 9.0900e+02, 9.8600e+02,
       1.1750e+03, 2.2000e+03, 8.5000e+03, 6.0550e+03, 9.2410e+03,
       2.4750e+03, 3.9630e+03, 6.2480e+03, 3.1750e+03, 2.0490e+03,
       5.8760e+03, 4.7310e+03, 2.4210e+03, 1.0440e+03, 3.3320e+03,
       2.4630e+03, 4.0000e+03, 3.3300e+03, 1.6310e+03, 2.0560e+03,
       5.0000e+03, 1.8800e+03, 4.5200e+02, 4.8000e+03, 2.8650e+03,
       5.7620e+03, 9.1800e+03, 3.7450e+03, 1.2920e+03, 2.6070e+03,
       3.4560e+03, 3.4360e+03, 5.3160e+03, 1.7790e+03, 1.3200e+03,
       4.6480e+03, 3.3610e+03, 2.2720e+03, 4.4460e+03, 1.4960e+03,
       1.5450e+03, 7.5900e+02, 3.2180e+03, 1.9600e+03, 6.0900e+02,
       8.3500e+02, 1.2950e+03, 2.4840e+03, 3.6880e+03, 2.1170e+03,
       2.8220e+03, 1.9980e+03, 2.9320e+03, 5.2960e+03, 5.2000e+03,
       2.0190e+03, 4.4970e+03, 2.4490e+03, 3.3580e+03, 3.8000e+03,
       4.1700e+03, 7.5000e+03, 3.1400e+03, 2.4000e+03, 1.8310e+03,
       2.0950e+03, 1.8450e+03, 9.2300e+02, 1.7240e+03, 4.1810e+03,
       5.1190e+03, 3.5570e+03, 3.6500e+03, 3.8140e+03, 1.3500e+03,
       2.6120e+03, 1.4810e+03, 2.5500e+03, 1.7970e+03, 5.5480e+03,
       1.8400e+03, 3.4000e+03, 3.0140e+03, 4.1980e+03, 1.1500e+03,
       2.7300e+03, 1.1070e+03, 1.1309e+04, 4.7570e+03, 5.8620e+03,
       5.7210e+03, 7.5310e+03, 1.4930e+03, 5.4270e+03, 2.9940e+03,
       3.7440e+03, 2.2280e+03, 4.5990e+03, 9.9000e+02, 1.7380e+03,
       2.0370e+03, 1.5360e+03, 1.5630e+03, 1.2550e+03, 3.6280e+03,
       1.4370e+03, 5.0210e+03, 1.3620e+03, 3.3210e+03, 1.4620e+03,
       1.1100e+03, 1.3220e+04, 2.1600e+03, 6.3380e+03, 6.4190e+03,
       4.2560e+03, 3.8150e+03, 1.9400e+03, 2.0350e+03, 4.7520e+03,
       4.3700e+03, 2.5790e+03, 2.9800e+03, 2.7820e+03, 1.9360e+03,
       3.6990e+03, 1.9320e+03, 1.3350e+03, 1.8930e+03, 2.0500e+03,
       2.6920e+03, 2.8610e+03, 2.1220e+03, 4.8910e+03, 2.0480e+03,
       2.8270e+03, 5.2100e+03, 2.9120e+03, 3.9800e+03, 3.1140e+03,
       1.3890e+03, 1.8740e+03, 1.7890e+03, 1.8700e+03, 3.7200e+02,
       9.5490e+03, 6.3000e+02, 2.3850e+03, 1.3300e+03, 8.2000e+02,
       3.4850e+03, 1.5900e+03, 2.1100e+03, 3.5270e+03, 4.0680e+03,
       3.9740e+03, 1.3800e+03, 3.5820e+03, 2.4400e+03, 2.7360e+03,
       1.2263e+04, 5.5350e+03, 7.0120e+03, 1.5590e+03, 2.9520e+03,
       8.3240e+03, 3.5000e+03, 1.5520e+03, 2.3530e+03, 4.7870e+03,
       3.3280e+03, 2.2900e+03, 4.0760e+03, 3.1220e+03, 3.9760e+03,
       5.3600e+03, 5.1520e+03, 2.6760e+03, 3.9010e+03, 4.0460e+03,
       1.8020e+03, 1.0400e+03, 2.9100e+03, 3.1500e+02, 3.2400e+02,
       1.7370e+03, 2.9720e+03, 3.4650e+03, 1.5230e+03, 4.2200e+03,
       3.5850e+03, 8.4800e+02, 5.7900e+03, 6.5490e+03, 3.1050e+03,
       1.3700e+03, 4.9000e+03, 3.5210e+03, 5.0010e+03, 4.5370e+03,
       1.4770e+03, 1.8890e+03, 3.2680e+03, 4.5160e+03, 4.1400e+03,
       4.5000e+03, 4.4090e+03, 9.8400e+02, 2.3900e+03, 7.0800e+02,
       4.3400e+02, 1.8850e+03, 5.9400e+02, 2.5140e+03, 2.3470e+03,
       2.7240e+03, 4.2600e+03, 4.0500e+02, 2.4900e+03, 3.6150e+03,
       1.1000e+03, 1.2400e+03, 1.6890e+03, 1.8200e+03, 1.2700e+03,
       1.0990e+03, 1.5000e+03, 6.3050e+03, 3.1780e+03, 4.7360e+03,
       1.7620e+03, 2.4290e+03, 7.0500e+03, 4.5510e+03, 7.3890e+03,
       4.2870e+03, 5.3720e+03, 6.7120e+03, 8.5020e+03, 5.6170e+03,
       2.8200e+03, 3.3270e+03, 2.3080e+03, 3.7320e+03, 4.3570e+03,
       5.5840e+03, 3.6000e+03, 3.0270e+03, 4.6800e+03, 5.2900e+03,
       2.3000e+03, 3.7360e+03, 5.2320e+03, 6.4050e+03, 3.7350e+03,
       3.9510e+03, 2.7170e+03, 4.5440e+03, 2.5110e+03, 3.5870e+03,
       3.6510e+03, 1.6450e+03, 1.3500e+04, 1.1000e+04, 1.7301e+04,
       2.7510e+03, 6.5460e+03, 4.8300e+03, 8.3110e+03, 5.6480e+03,
       5.9910e+03, 4.5180e+03, 6.4020e+03, 3.8210e+03, 2.6700e+03,
       1.4720e+03, 6.5020e+03, 3.0200e+02, 3.2450e+03, 6.3700e+02,
       2.4340e+03, 3.8300e+03, 5.3500e+03, 3.9140e+03, 1.8600e+03,
       3.1870e+03, 7.8840e+03, 3.7810e+03, 2.0900e+03, 3.9700e+03,
       1.3170e+03, 6.1100e+03, 7.5890e+03, 3.9520e+03, 3.0350e+03,
       3.0610e+03, 2.5700e+03, 1.6340e+03, 2.0290e+03, 2.0430e+03,
       2.9780e+03, 3.9300e+03, 1.8060e+04, 9.3600e+02, 3.7030e+03,
       1.9750e+03, 2.2990e+03, 5.7040e+03, 1.9100e+03, 4.2700e+03,
       2.5020e+03, 2.2760e+03, 3.5400e+03, 1.1829e+04, 6.4320e+03,
       7.3290e+03, 9.1000e+03, 1.3400e+03, 2.4500e+03, 5.4540e+03,
       2.1130e+03, 1.7600e+03, 4.6200e+03, 4.5800e+03, 4.4000e+02,
       1.9030e+03, 2.9210e+03, 1.0741e+04, 1.2010e+03, 2.8100e+03,
       7.0400e+03, 2.8900e+03, 3.3090e+03, 1.7110e+03, 4.2800e+03,
       7.0200e+03, 1.8300e+03, 7.7900e+02, 3.2000e+02, 5.7100e+02,
       4.2720e+03, 5.3090e+03, 7.6000e+02, 2.3813e+04, 5.0292e+04,
       8.6160e+03, 6.1200e+03, 9.8500e+03, 4.4200e+03, 6.2000e+03,
       3.6170e+03, 6.4960e+03, 9.6000e+02, 4.8700e+02, 2.9400e+03,
       3.0300e+03, 3.9600e+03, 8.0000e+03, 4.0000e+04, 1.2870e+03,
       2.6486e+04, 2.6470e+03, 1.0557e+04, 5.0360e+03, 3.7460e+03,
       3.2270e+03, 4.9960e+03, 5.2840e+03, 1.0538e+04, 9.2300e+03,
       1.9900e+03, 2.4200e+03, 4.9040e+03, 3.8020e+03, 2.0640e+03,
       1.1730e+03, 1.8900e+03, 1.0700e+03, 2.6950e+03, 2.6140e+03,
       2.6290e+03, 3.9550e+03, 1.0968e+04, 1.0961e+04, 3.0870e+03,
       3.7920e+03, 4.3070e+03, 4.9600e+02, 3.4150e+03, 8.6600e+02,
       2.1000e+03, 2.6820e+03, 4.2210e+03, 2.0270e+03, 8.1400e+02,
       3.1990e+03, 1.2000e+02, 3.1320e+03, 1.2200e+03, 6.0520e+03,
       4.3800e+03, 2.4230e+03, 3.3490e+03, 2.6210e+03, 2.5920e+03,
       2.4830e+03, 3.8540e+03, 1.9610e+03, 6.2400e+03, 3.3650e+03,
       3.5560e+03, 6.0400e+02, 8.7000e+02, 1.6710e+03, 1.3450e+03,
       5.8350e+03, 2.7810e+03, 3.6660e+03, 3.4370e+03, 5.1910e+03,
       2.0790e+03, 3.4300e+03, 1.7460e+03, 3.0080e+03, 1.4260e+03])

In [16]:
df['event_name'].unique()

<StringArray>
[                                  'Mandala Spirit',
                                      'Röntgenlauf',
                    'HIMALAYAN 100 MILE STAGE RACE',
                                    'LAKE BIWA 100',
                            'Lianyungang 168 Ultra',
                     'Walking Dead Ultra 100 Miles',
                                     'TsaiGu Trail',
                            'ULJU TRAIL NINE PEAKS',
                                'Albatross Ultrail',
                              'Trail Del Cinghiale',
 ...
                              'Chiltern Hills 100K',
                       'Upriver Running Fall Races',
               'KarpatyRun -  BRATISLAVA TRAIL RUN',
                     'White Bride Ultra Gelendzhik',
                                       'gapencimes',
                               'Cederberg Traverse',
                                  'The Blackall100',
 'PÉTRA WADI RUM TRAIL CHALLENGE Trail To Be Alive',
                                   'Ultra X Rwanda',
        'Pharaons Pyramids Trail Trail To Be Alive']
Length: 689, dtype: str

In [ ]:
df.nunique()    #ustundagi calsslar soni

event_date           182
name                1002
distance_km          889
elevation_gain_m     964
elevation_loss_m     949
gpx_url              813
event_name           689
country               81
locality             671
source_url          1233
source                 1
schema_version         1
scraped_at             1
dtype: int64

In [ ]:
df['locality'].nunique() #ustundagi classlar soni

671

In [19]:
df['name']

0                         Mandala Spirit I
1                            Ultramarathon
2       35th Himalayan 100 Mile Stage Race
3           5th Himalayan 100 K Stage Race
4                                      100
                       ...
1228                            Blackall50
1229       PÉTRA WADI RUM TRAIL  CHALLENGE
1230                                 110km
1231                                  50km
1232              Pharaons Pyramids  Trail
Name: name, Length: 1233, dtype: str

In [20]:
df['distance_km']

0       305.44
1        63.00
2       161.00
3       100.00
4       163.69
         ...
1228     52.25
1229    113.00
1230    110.00
1231     50.00
1232     69.00
Name: distance_km, Length: 1233, dtype: float64

In [21]:
df[['name', 'locality','country']]

                                    name               locality country
0                       Mandala Spirit I                 Laprak     NPL
1                          Ultramarathon              Remscheid     DEU
2     35th Himalayan 100 Mile Stage Race          manebhanjyang     IND
3         5th Himalayan 100 K Stage Race          manebhanjyang     IND
4                                    100              Komonocho     JPN
...                                  ...                    ...     ...
1228                          Blackall50               MAPLETON     AUS
1229     PÉTRA WADI RUM TRAIL  CHALLENGE                 Madaba     JOR
1230                               110km                Ruhondo     RWA
1231                                50km                Ruhondo     RWA
1232            Pharaons Pyramids  Trail  Al Qahirah al Jadidah     EGY

[1233 rows x 3 columns]

===>>> unique 3 ta attribute qabul qilmaydi

In [23]:
df[['name', 'locality','country']].nunique

<bound method DataFrame.nunique of                                     name               locality country
0                       Mandala Spirit I                 Laprak     NPL
1                          Ultramarathon              Remscheid     DEU
2     35th Himalayan 100 Mile Stage Race          manebhanjyang     IND
3         5th Himalayan 100 K Stage Race          manebhanjyang     IND
4                                    100              Komonocho     JPN
...                                  ...                    ...     ...
1228                          Blackall50               MAPLETON     AUS
1229     PÉTRA WADI RUM TRAIL  CHALLENGE                 Madaba     JOR
1230                               110km                Ruhondo     RWA
1231                                50km                Ruhondo     RWA
1232            Pharaons Pyramids  Trail  Al Qahirah al Jadidah     EGY

[1233 rows x 3 columns]>

In [24]:
df[['name', 'locality','country']].any()

name        True
locality    True
country     True
dtype: bool

In [25]:
df[['name', 'locality','country']].info()

<class 'pandas.DataFrame'>
RangeIndex: 1233 entries, 0 to 1232
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      1233 non-null   str
 1   locality  1225 non-null   str
 2   country   1233 non-null   str
dtypes: str(3)
memory usage: 29.0 KB

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1233 entries, 0 to 1232
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   event_date        1233 non-null   str
 1   name              1233 non-null   str
 2   distance_km       1233 non-null   float64
 3   elevation_gain_m  1141 non-null   float64
 4   elevation_loss_m  1134 non-null   float64
 5   gpx_url           816 non-null    str
 6   event_name        1233 non-null   str
 7   country           1233 non-null   str
 8   locality          1225 non-null   str
 9   source_url        1233 non-null   str
 10  source            1233 non-null   str
 11  schema_version    1233 non-null   int64
 12  scraped_at        1233 non-null   str
dtypes: float64(3), int64(1), str(9)
memory usage: 125.4 KB

In [27]:
df.isnull().sum()

event_date            0
name                  0
distance_km           0
elevation_gain_m     92
elevation_loss_m     99
gpx_url             417
event_name            0
country               0
locality              8
source_url            0
source                0
schema_version        0
scraped_at            0
dtype: int64

In [28]:
df.isnull().any()

event_date          False
name                False
distance_km         False
elevation_gain_m     True
elevation_loss_m     True
gpx_url              True
event_name          False
country             False
locality             True
source_url          False
source              False
schema_version      False
scraped_at          False
dtype: bool

CONDITIONS

In [35]:
a=1
if a>0:
    print('Yaxshi')
elif a<0:
    print('Yomon')
else:
    print('nol')

Yaxshi

In [37]:
baxo=5
if baxo==5:
    print('alo')
elif baxo==4:
    print('yaxshi')
elif baxo==3:
    print('ortacha')
elif baxo==2:
    print('yomon')
else:
    print('xatolik bor yoki juda yomon')

alo

Imtihondan otish ball

In [4]:
ball = 80

if ball < 0 or ball > 100:
    print('xatolik: ball 0 dan 100 gacha bolishi kerak')
elif ball >= 86:
    print('alo - imtihondan otdi')
elif ball >= 71:
    print('yaxshi - imtihondan otdi')
elif ball >= 60:
    print('ortacha - imtihondan otdi')
else:
    print('yomon - imtihondan otmadi')

yaxshi - imtihondan otdi

Passport uchun

In [8]:
yosh = 10

if yosh < 0:
    print('xatolik: yosh manfiy bolishi mumkin emas')
elif yosh >= 16:
    print('pasport olishingiz mumkin')
else:
    print('hali pasport olish mumkin emas')

hali pasport olish mumkin emas

Ob havo

In [14]:
harorat = -1

if harorat > 30:
    print(' juda issiq')
elif harorat >= 15:
    print('iliq')
elif harorat >= 0:
    print('salqin')
else:
    print('sovuq')

sovuq

Login

In [18]:
login = ('Jurat')
parol = ('Jurat1')

if login == 'Jurat' and parol == 'Jurat19':     #parol "Jurat19"
    print('Xush kelibsiz!')
elif login == 'Jurat':              #elif loginni tekshiradi u togri bolsa parolni xato korsatadi.
    print('parol notogri')
else:
    print('bunday foydalanuvchi yoq')

parol notogri

Svetafor

In [23]:
rang = 'yashil'

if rang == 'qizil':
    print('toxta')
elif rang == 'sariq':
    print('tayyorlan')
elif rang == 'yashil':
    print('yur')
else:
    print('xatolik: bunday rang yoq')

yur